export { default as Navbar } from "./navbar";
export { default as Featured } from "./featured";
export { default as TrustedBy } from "./trustedBy";
export { default as CatCard } from "./catCard";
export { default as Footer } from "./footer";
export { default as GigCard } from "./gigCard";
export { default as ProjectCard } from "./projectCard";
export { default as Slide } from "./slide";
export { default as Loader } from "./loader";